### ISSUE TITLE
In-game manuals ignore custom recipes.

### ISSUE THREAD

**Issue by OneEyeMaker** [McJtyMods/RFTools#386] opened 2015-11-18 13:54 UTC
Hello!
I found strange bug in in-game manuals (books). If I change any RFTools recipe with Minetweaker, I can't see it in books. I see `{rb:unlocalizedNameOfBlockOrItem}` instead.
http://imgur.com/XuhVqa3

Please, fix that (if it is possible).
P. S. Sorry for my English, I'm from Russia.

**Comment by McJty** [comment] 2015-11-18 13:55
That's strange... The manual is simply taking the current recipe from MC itself. Can you tell me exaclty how you changed the recipe? i.e. the MT script?

**Comment by OneEyeMaker** [comment] 2015-11-18 14:53
```
//MT Script
<ore:plateHeavyDutyT3>.add(<GalacticraftMars:item.itemBasicAsteroids:0>);
recipes.remove(<rftools:machineFrame:0>);
recipes.remove(<rftools:machineBase:0>);
recipes.addShaped(<rftools:machineFrame:0>, [
    [<ore:compressedIron>, <Forestry:thermionicTubes:11>, <ore:compressedIron>],
    [<ore:chipsetGold>, <ore:plateHeavyDutyT3>, <ore:chipsetGold>],
    [<ore:compressedIron>, <Forestry:thermionicTubes:11>, <ore:compressedIron>]
]);
recipes.addShapeless(<rftools:machineBase:0> * 2, [<rftools:machineFrame:0>]);
recipes.addShapeless(<rftools:machineFrame:0>, [<rftools:machineBase:0>, <rftools:machineBase:0>]);
```

**Comment by McJty** [comment] 2015-11-18 15:10
I think the problem is that you made the recipe shapeless and the manual can't work with that. Can you make the recipe shaped instead?

**Comment by OneEyeMaker** [comment] 2015-11-18 15:22
The problem isn't only in type of recipe (shaped/shapeless). I edited recipes for other blocks in RFTools; and I noticed, that I can see recipe in book only in one case - if recipe doesn't contains items from another mods and recipe ```instanceof ShapedRecipes``` (not ```ShapedOreRecipe```).

I. e., mod can't render recipes with OreDictionary entries.

**Comment by OneEyeMaker** [comment] 2015-11-18 15:24
```
// I don't see this recipe in book.
recipes.remove(<rftools:rfMonitorBlock:0>);
recipes.addShaped(<rftools:rfMonitorBlock:0>, [
    [<ore:gearIron>, <ore:chipsetComp>, <ore:gearIron>],
    [<ore:chipsetRed>, <rftools:machineFrame:0>, <ore:chipsetRed>],
    [<ore:gearIron>, <ore:chipsetComp>, <ore:gearIron>]
]);
```

**Comment by OneEyeMaker** [comment] 2015-11-18 15:29
```
//But I see that:
recipes.remove(<rftools:dimensionEditorBlock:0>);
recipes.addShaped(<rftools:dimensionEditorBlock:0>, [
    [null, <rftools:infusedDiamondItem:0>, null],
    [<rftools:infusedDiamondItem:0>, <rftools:dimensionBuilderBlock:0>, <rftools:infusedDiamondItem:0>],
    [null, <rftools:infusedDiamondItem:0>, null]
]);
```

**Comment by OneEyeMaker** [comment] 2015-11-18 16:29
As I understand, problem is:
https://github.com/McJty/McJtyLib/blob/master/src/main/java/mcjty/lib/gui/widgets/TextPage.java#L282

**Comment by McJty** [comment] 2015-11-18 18:36
Indeed. I'll try to fix this but not for next release. Too close to release

**Comment by OneEyeMaker** [comment] 2015-11-22 08:58
Maybe, that will be helful:
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/lib/manual/ManualPages.java
Only keep in mind, that this code should run after (pre-)initialization of Minetweaker (otherwise, you'll get another problem: https://github.com/BluSunrize/ImmersiveEngineering/issues/677)

**Comment by MichaelHillcox** [comment] 2020-03-26 00:19
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Closed** 2020-03-26 00:19 UTC
Labels: bug
