### ISSUE TITLE
[1.10.2] Randomly generated dimension void with gravel and sand

### ISSUE THREAD

**Issue by operinko** [McJtyMods/RFTools#1351] opened 2017-09-03 22:50 UTC
As stated, I just randomly generated a dimension (blank dimension card in a builder), upon entering it around 29k sand and gravel (EntityFallingBlock) blocks started falling towards the void.
This caused the tickrate of the server to fall down to >1 (0.22 TPS was the last I noticed before nuking the dimension).

This is now the 3rd time this has happened on our server in a relatively short time, is there a way to blacklist sand and gravel on any dimensions that contain void in any way?

Modpack: Age of Engineering 1.0.4
RFTools Dimensions version: rftoolsdim-1.1x-5.04

**Comment by MrNinja93** [comment] 2017-09-03 23:11
Assuming it's feasible from a coding perspective a config option to replace gravity affected blocks with the inverted world equivalents might be a suitable way to get around it, generate levarG and dnaS instead of Gravel/Sand

**Comment by McJty** [comment] 2017-09-05 10:49
BTW. Please report dimension problems to the right mod (RFTools Dimensions is a separate mod)

**Comment by McJty** [comment] 2017-09-05 10:50
As to this problem. What kind of world was it? The issue is that gravel and sand can be generated by biomes. Say you have a floating islands world and it is a desert biome then there is a big chance that many islands will be made out of sand. There is nothing that I can do about that as that is done by the biomes. Replacing with the 'non-gravity' versions is really not an option as those are really different blocks

**Comment by operinko** [comment] 2017-09-05 12:43
Seemed to me to be a plain void world, no terrain generation, with a random feature deciding to be sand/gravel.

**Comment by McJty** [comment] 2017-09-05 12:45
Can you show me the dimension info? (sneak-right click with the dimension tab in your hand)

**Comment by operinko** [comment] 2017-09-05 12:59
The dimension in question was nuked (safedel), and I'm quite sure I don't have the dimension tab anymore at hand, though I'm unable to check currently as I'm away from home.

Will see what I can do once I get back

**Comment by operinko** [comment] 2017-09-06 10:34
Nope, don't have the dimension tab anymore :(

**Comment by DeFazer** [comment] 2017-09-12 12:34
Idea: add a post-generation option to custom dimensions so that if sand/gravel have a block of air below them and a sand/gravel above them (should match all these free-floating sand spheres and gravel islands), they are replaced with sandstone/stone respectively. Or, with a special Static Sand/Gravel blocks added by the mod for this specific purpose - they are like their respective counterparts in every other aspect - texture, type, mining level - drop them when mined, just do not fall. Hey, they could even be automatically generated to support similar blocks from other mods. This should definitely help combat the lag associated with collapsing blocks like these two.

**Comment by McJty** [comment] 2017-09-12 12:45
Scanning all generated chunks for this would add some performance penalties though. i.e. it would slow down chunk generation a bit

**Comment by DeFazer** [comment] 2017-09-12 15:24
Some performance penalties would still be better than a server death from lag. In addition, this option could be limited to specific generation settings, something along the lines of (("FallingBlock Sphere"||"FallingBlock Scattered Sphere")&&(Type!=Solid)||(Type==Solid && Material==FallingBlock)||...). Given that there is a quite small list of existing features and terrain generation options, this predicate could be easily fine-tuned. 
Also, spheres, tendrils and the like could be generating supports themselves, further reducing the need for a complete chunk scan.

**Comment by McJty** [comment] 2017-09-12 15:47
Well falling blocks like sand are already excluded from worldgen. Except that I have no control over biomes. So in practice these falling blocks can occur anywhere

**Comment by MichaelHillcox** [comment] 2020-03-26 03:37
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Closed by MichaelHillcox** 2020-03-26 03:37 UTC
