### ISSUE TITLE
Remote storage in tablet loses items randomly!

### ISSUE THREAD

**Issue by memotype** [McJtyMods/RFTools#1178] opened 2017-05-08 07:17 UTC
I've had this happen a few times now. When shift-clicking items from my inventory in to my tablet, the item/stack is simply lost. This is obviously VERY annoying... :(

I have a remote storage module in my tablet linked to a remote storage block. I'm not sure how to reliably reproduce it, but in the past 6 hours or so of game play, it's happened about 3 times. I don't remember exactly what I was doing the first 2 times, but the last time here is exactly what I did, in case it helps to track this down.

I have a crafting recipe for a blue XNet connector saved as the last saved recipe in my tablet, with the lapis replaced with blue floral powder (from Botania). I had double-clicked it so the recipe was loaded in the crafting grid. Then, I pulled 4 blue petals out of the tablet. I placed them on the ground and bone-mealed them to tall flowers, sheared them, then placed all those petals down, and repeated to get a full stack of petals. Then I pulled my mortal and pestle out of the tablet, and in my 2x2 crafting grid, I turned 60 of the petals in to floral powder (saving 4 petals). I then opened the tablet and shift-clicked the 4 petals, 60 blue powder, 44 bone meal and the mortal and pestle in to the tablet. Then when I tried to click the 1/4/8/X buttons to craft the XNet connector, it said I had no blue powder. I looked in the tablet inventory and it simply wasn't there. The bone meal was gone too. The 4 petals and the mortar and pestle were there though.

Obviously not a huge loss, but it makes me afraid to use the tablet... The first time this happened, I lost half a stack of gold ingots :(

I don't know if it's because the crafting recipe was loaded that maybe confused something in the code....? I'm just guessing.

Also, I tried fully reloading Minecraft, and the items are still gone.

I'm playing on FTB Beyond, Minecraft 1.10.2. I updated to the latest RFTools 6.0.0 and XNet 1.3.1 after the first time it happened. I can upload my save file to Dropbox or something if you want to see if you can reproduce it in my world. Also, feel free to ask me any questions about this issue that I might have left out.

Thanks.

**Comment by McJty** [comment] 2017-05-08 08:23
Hmm. I doubt it is the tablet that is destroying items as that doesn't hold the items itself. It seems more likely they are lost elsewhere. On the other hand this would be very weird really and I have never heard this reported before. Are you really really sure they are not ending up elsewhere that you are not accounting for?

I mean can there be anything else elsewhere that is using that bone meal?

**Comment by memotype** [comment] 2017-05-08 16:04
I'm not that far in to the game, I don't have much automation. The only things that pull out of my storage network are a few EnderIO Vats, but they only pull out melons and potatos, and it's on a different remote storage ID anyway. Besides, I had a stack of floral blue powder in there before, and it never got sucked out anywhere, so I don't know how it would after putting in a new stack. I'll keep trying to reproduce it to see if I can narrow down when it happens.

**Comment by memotype** [comment] 2017-05-08 16:31
I've been playing around with it a bit more (basically just pulling items out and putting them back in over and over in different ways) and so far I haven't lost any items, but I did notice a few things:

1) A few times I would shift-click items in to the tablet, and the tablet inventory would flicker, and the items would pop back in to my inventory.

2) A couple of times, I would shift-click something from my hotbar, and instead of going in to the tablet/storage, it would just move the item to my inventory, kind of like when you try to shift-click something in to a full chest.

2) When looking at the tablet UI, every now and then the contents will flicker. I assume it's refreshing the contents or something. So maybe there's a timing issue where if you shift-click items in right when it's refreshing (or whatever is causing the flicker) there is a race-condition or something where items can be lost or can't be inserted depending on the timing?

Also, I know the tablet itself doesn't hold items, so maybe the title of my issue report is wrong, but they are definitely getting lost *somewhere* in the remote storage network.

**Comment by memotype** [comment] 2017-05-09 14:50
Ok, so I wrote a Sikuli script to insert and pull out an item over and over, and I let it run all night, and wasn't able to reproduce this. However, every now and then, when shift-clicking the item in to the tablet, the item would end up stuck on my cursor, and when exiting the table GUI it would pop out on the ground, so maybe that's what happened before and I didn't notice it falling on the ground. So, I guess in the meantime, go ahead and close this bug.

**Comment by memotype** [comment] 2017-05-11 14:38
The tablet/remote storage/something is definitely losing items and I've finally been able to reliably reproduce the issue. The problem happens when mousing over the 1/4/8/X crafting buttons while the inventory is refreshing. I'll upload my Sikuli script and the test world I set up for this if you want to try to reproduce it that way (you might have to redo some of the screenshots in the Sikuli script since you probably have a different resolution, etc).

**Comment by McJty** [comment] 2017-05-11 15:00
What is sikuli?

**Comment by McJty** [comment] 2017-05-11 15:20
Can you tell me what inventories you all have attached to your storage scanner? i.e. where are the items that it needs for the recipe you're hovering over coming from?

**Comment by memotype** [comment] 2017-05-11 17:50
Sikuli is a test automation scripting engine. It works by pattern matching screen clippings to find GUI elements to click on. http://www.sikulix.com/

The setup in my test world is pretty simple. I have a a Tablet with a Remote Storage Module linked to the ID of a Storage Module Tier 3 in a Remote Storage block.

**Comment by memotype** [comment] 2017-05-11 17:56
In the Tablet, I have a recipe for a Comparator saved in the bottom saved recipes slot and 8 redstone torches in the remote storage.

The Sikuli script just makes it easier to do the same thing over and over. What I have the script doing to reproduce this is:

1) Click on the 8 redstone torches, and then click to drop them in the player inventory.
2) Shift-click the torches back in to the remote storage.
3) Double-click the saved comparator recipe to load it.
4) Mouse over the 4, X, 8, and 1 crafting buttons, in that order.

Then it just right-clicks the comparator icon in the crafting panel to clear it, hit ESC to exit the tablet GUI, right-click to re-open it. After that it just loops and does it all again.

Running this script, it takes about 2-5 minutes until the redstone torches vanish from the remote storage. It happens when you're mousing over one of the 1/4/8/X crafting buttons. If the remote inventory flickers and refreshes while you're mousing over one of these (I think it's whenever it mouses over one that causes the ingredients to go red) then the torches a gone from the inventory.

**Comment by McJty** [comment] 2017-05-11 17:57
yes, but to what inventories is the scanner connected? Where would the ingredients for the comparator come from?

**Comment by memotype** [comment] 2017-05-11 17:58
No scanner. It's just a Remote Storage Module linked to the Storage Module Tier 3 in the Remote Storage block.

**Comment by McJty** [comment] 2017-05-11 17:59
Ah hmm. Ok I totally misunderstood (misread)
Too many things to do at once. I'll check it out then. I may be able to reproduce this

**Comment by memotype** [comment] 2017-05-11 18:01
No problem, I understand you're very busy. I love your mods and I know you have a lot of them, and a lot of things to work on. I just feel like this is a pretty major bug. I very much appreciate you taking a look at this.

I emailed you a link to a shared DropBox folder that has a world download with my test setup so hopefully that will make it easier to see exactly how I have this set up.

**Comment by ShadwDrgn** [comment] 2017-05-16 17:09
I've been having this issue too. I definitely get the feeling it's been related to the crafting buttons. I just lost some pulsating iron to this and early on lost all my emeralds :(.

**Comment by McJty** [comment] 2017-05-16 17:15
Any information you can give me to help reproduce this would be great. I have failed to do so. Perhaps a small setup and with information about the exact setup and so on

**Comment by ShadwDrgn** [comment] 2017-05-16 17:16
I'm just using the storage tab and a remote storage block. If I manage to figure out how to make it always happen, I'll let you know.

**Comment by McJty** [comment] 2017-05-16 17:16
That would be great

**Comment by ShadwDrgn** [comment] 2017-05-16 17:18
I just made it happen. I had a recipe for a travel anchor in the display. I shift clicked a pulsating iron nugget out of the tab. Shift clicked it back in. Shift clicked it back out AGAIN, and back in again. Then I moused over several of the crafting numbers. so far i've gotten it to happen twice in a row.

**Comment by ShadwDrgn** [comment] 2017-05-16 17:23
I can now narrow it even further.
Place travel anchor in recipe
Place pulsating iron nugget from inventory to storage tab with shift click
Mouse over x in crafting area for "craft stack"
Leave mouse there. Inventory will flash over and over and pulsating iron nugget will vanish

**Comment by McJty** [comment] 2017-05-16 17:24
That's already pretty good but it would be perfect if you can reproduce it with only vanilla recipes as that's easier in my dev environment

**Comment by ShadwDrgn** [comment] 2017-05-16 17:25
It definitely doesn't seem to happen with beacon and a plank. I can also add that i do NOT have any of the materials for the travel anchor in the tab.

**Comment by ShadwDrgn** [comment] 2017-05-16 17:27
The inventory still flashes over and over mousing over the x. The plank just doesn't vanish

**Comment by ShadwDrgn** [comment] 2017-05-16 17:30
Use a beacon for the recipe and place one glass in. mouse over the x. Glass vanishes

**Comment by McJty** [comment] 2017-05-16 17:32
Ok, thanks. I'll try to reproduce it like that. So is the remote storage completely empty or does it contain some stuff?

**Comment by ShadwDrgn** [comment] 2017-05-16 17:35
it contains a bunch of stuff. 103 items in the bag none of which are glass nether stars or obsidian. excepting the 1 glass i shift click in.

**Comment by memotype** [comment] 2017-05-16 19:33
@ShadwDrgn good point, you can just hover the mouse over the crafting buttons. I don't think it has anything to do with the shift-clicking of the item, it just has to do with when there aren't enough items to craft the number you're mousing over, and so it is showing a red background for the items you don't have enough of.

I think I've narrowed down an easy way to reproduce this.

Items needed:

1. Remote Storage Block
2. Storage Module Tier 3
3. Remote Storage Module (**not** Storage Control Module)
4. Storage Module Tablet
5. Two redstone torches

Steps to reproduce:

1. Place Remote Storage block
2. Insert Storage Module Tier 3
3. Insert and remove Remote Storage Module to link
4. Craft Storage Module Tablet with Remote Storage Module
5. Open Tablet GUI
6. Search for "Redstone Comparator" in JEI, and click "+" to load the recipe in the crafting grid.
7. Shift-click two redstone torches in to the remote storage
8. Mouse over the "X" crafting button, but don't click it.
9. Wait a few seconds/minutes until the inventory flashes. The two redstone torches will disappear from the remote storage.

**Comment by McJty** [comment] 2017-05-22 08:06
My big problem is step 11. I have never been able to reproduce the flashing inventory issue (see https://github.com/McJty/RFTools/issues/1196). I think what is happening at that point is the clue to this problem but I don't know what it is and I never saw it happen

**Comment by memotype** [comment] 2017-05-22 18:22
Are you sure you're using a Remote Storage Module and not a Storage Control Module? I ask because it's easy to get them confused, and you kept asking about Storage Scanners.

**Comment by McJty** [comment] 2017-05-22 18:33
yes, I'm using remote storage module. In the beginning I thought it was about those but now I know it is not :-)

**Comment by ShadwDrgn** [comment] 2017-05-22 22:22
Ok new steps to reproduce:

creative powercell connected to remote storage.
level 3 module in remote storage (cross-dim disabled) (top left)
link a remote storage module. Place in top left slot. to link
Combine module and tablet. Charge tablet to full.
Place Iron Pickaxe, half charged adv charged porter, and full charged porter in tablet
place beacon recipe in crafting grid (do not store)
mouse over craft a stack button for 2 seconds
if inventory doesn't flash mouse off of stack button and back on 2 more seconds

Once you've reproduced this far. get 1 glass in your hotbar.
Open tablet.
place glass in tablet
cause flash
glass gone.

**Comment by ShadwDrgn** [comment] 2017-05-22 22:34
If the above doesn't work to reproduce let me know and i'll make an instance with NOTHING but rftools installed to see if i can further test

**Comment by McJty** [comment] 2017-05-25 04:16
Well I followed exactly the steps above and still cannot reproduce it

**Comment by McJty** [comment] 2017-05-25 04:24
I also switched to 1.10.2 in multimc (made a small test pack there) because my dev env is 1.11.2. But also in 1.10.2 I cannot reproduce this if I follow exactly those steps

**Comment by siccaxe** [comment] 2017-05-28 23:02
Not really my place to say, but could this be an issue with Inventory Tweaks (mod)? I've had similar things happen with other inventory systems and I've see reports of this kind of thing attributed to the mod. 

Again, not my place and I don't mean to point fingers, just thought you might consider other mods since you cant reproduce.

**Comment by memotype** [comment] 2017-05-30 11:43
I was actually thinking the same thing yesterday. I haven't had time to mess with it much recently, but I do plan on setting up a small test pack with just RFTools, and if I can't reproduce it, try again with just RFTools and Inventory Tweaks to see if that makes the difference.

**Comment by McJty** [comment] 2017-05-30 11:44
Thanks a lot for the effort you are putting in this! I appreciate it

**Comment by falizure** [comment] 2017-07-13 20:10
i can confirm this report, both on behalf of 1 of the players on my server and myself having confirmed it, for us it seams to occur when you have a recipe selected in the storage tablet module and have the items in the tablet the screen will flicker and every xth time itll just delete that entire set of items, for a moment i was noticing the screen flicker over 4 as well but it stopped and i have not been able to get it to do do again, this is with a remote storage module with 4 different modules slotted into the bay, it seams to happen no matter which module you have selected. (when i was trying to assist them i noticed the remote storage block seams to be falsely reporting the number of objects inside that particular module, when i took out that module however and slotted it into a normal storage block it updated to show the correct items remaining in the module, could it be the items are still being stored but are unaccessable and doing so forces a update to the inventory?)

**Comment by McJty** [comment] 2017-07-19 06:25
https://github.com/McJty/RFTools/issues/1294

**Comment by McJty** [comment] 2017-07-19 17:34
I hopefully fixed this in 6.12. Let me know if the fix helps

**Comment by ShadwDrgn** [comment] 2019-07-28 18:39
I believe this to be fixed. not positive. sorry about years later :D

**Comment by MichaelHillcox** [comment] 2020-03-26 03:14
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Closed** 2020-03-26 03:14 UTC
