### ISSUE TITLE
Crashes in rftools dimensions

### ISSUE THREAD

**Issue by mika1369** [McJtyMods/RFTools#1059] opened 2017-03-01 00:18 UTC
No specific situations, although ive only crashed in rftools dimensions, this is in the skyfactory 3 modpack.
[crash-2017-02-27_01.02.07-server.txt](https://github.com/McJty/RFTools/files/809349/crash-2017-02-27_01.02.07-server.txt)
[crash-2017-02-15_23.55.33-client.txt](https://github.com/McJty/RFTools/files/809351/crash-2017-02-15_23.55.33-client.txt)
[crash-2017-02-15_23.34.44-client.txt](https://github.com/McJty/RFTools/files/809352/crash-2017-02-15_23.34.44-client.txt)
[crash-2017-02-15_23.30.41-client.txt](https://github.com/McJty/RFTools/files/809348/crash-2017-02-15_23.30.41-client.txt)
[crash-2017-02-13_08.25.41-client.txt](https://github.com/McJty/RFTools/files/809347/crash-2017-02-13_08.25.41-client.txt)
[crash-2017-03-01_01.15.43-server.txt](https://github.com/McJty/RFTools/files/809350/crash-2017-03-01_01.15.43-server.txt)
[crash-2017-02-28_23.47.06-server.txt](https://github.com/McJty/RFTools/files/809353/crash-2017-02-28_23.47.06-server.txt)
[crash-2017-02-28_07.30.03-server.txt](https://github.com/McJty/RFTools/files/809355/crash-2017-02-28_07.30.03-server.txt)
[crash-2017-02-27_20.57.37-server.txt](https://github.com/McJty/RFTools/files/809354/crash-2017-02-27_20.57.37-server.txt)
[crash-2017-02-27_16.24.00-server.txt](https://github.com/McJty/RFTools/files/809356/crash-2017-02-27_16.24.00-server.txt)
[crash-2017-02-27_01.05.52-server.txt](https://github.com/McJty/RFTools/files/809357/crash-2017-02-27_01.05.52-server.txt)

[2017-02-28-7.log.gz](https://github.com/McJty/RFTools/files/809363/2017-02-28-7.log.gz)
[2017-02-28-3.log.gz](https://github.com/McJty/RFTools/files/809365/2017-02-28-3.log.gz)
[2017-02-28-2.log.gz](https://github.com/McJty/RFTools/files/809369/2017-02-28-2.log.gz)
[2017-02-28-1.log.gz](https://github.com/McJty/RFTools/files/809367/2017-02-28-1.log.gz)
[2017-02-28-6.log.gz](https://github.com/McJty/RFTools/files/809368/2017-02-28-6.log.gz)
[2017-02-28-5.log.gz](https://github.com/McJty/RFTools/files/809366/2017-02-28-5.log.gz)
[2017-02-28-4.log.gz](https://github.com/McJty/RFTools/files/809370/2017-02-28-4.log.gz)

**Comment by mika1369** [comment] 2017-03-01 00:21
I have attached all i could find that seemed relevant, please do let me know if more are required

**Comment by McJty** [comment] 2017-03-01 04:23
Very little of those logs are crashing in rftools dimensions. What makes you point to this mod?

**Comment by mika1369** [comment] 2017-03-01 15:25
I'm pretty sure I was in Rftools dimensions at the time of all the crashes, let me just go trough the logs real quick, could very well be remembering wrong

**Comment by McJty** [comment] 2017-03-01 15:27
Well yes. But are you blaming the nether when (for example) a furnace from mod X crashes in the nether? The fact that stuff crashes in rftools dimensions doesn't always mean it is caused by rftools dimensions :-)

**Comment by mika1369** [comment] 2017-03-01 15:29
Oh, i am aware, I just find it suspicious that I crash doing nothing in a rftools dimension, but not in my way too compact and machine heavy overworld.

I do apologise if I have put blame where it is not due.

Most, if not all of the crashes have been while exploring, could loading, unloading of chunks/blocks simply be overloading my client be the issue? - and could you possibly know if i can check this?

**Comment by mika1369** [comment] 2017-03-01 16:13
Just opened one of those .gz files, and realised they are encoded, and therefore looks like gibberish, so don't know if you can use those.

the ones I attached here might be more relevant, had to put them in a zip, as Githup does not like the .log extension



[Logs.zip](https://github.com/McJty/RFTools/files/811281/Logs.zip)

**Comment by MichaelHillcox** [comment] 2020-03-26 02:50
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Closed by MichaelHillcox** 2020-03-26 02:50 UTC
Labels: RFTools Dimensions
