### ISSUE TITLE
[1.10.2] Clearing Fortune Quarry not mining Crystals, Spawners or Water

### ISSUE THREAD

**Issue by xenoflot** [McJtyMods/RFTools#761] opened 2016-09-28 15:17 UTC
Hi McJty,

I'm running my first clearing, fortune quarry at the moment. Inspecting the hole-in-progress, it appears that Resonating Crystals are not being mined. I also found a Spawner and its loot chest. 

Further, while the quarry is clearing lava, it appears to not be destroying water source blocks. I've been left with great towers of water flowing down from those source blocks.

Finally, a related suggestion if I may, rather than placing blue structure blocks to cover air blocks on the edges of a quarry hole, I think it would be better to look outside the quarry area by 1 or two blocks and replace lava & water source with dirt. This would help reduce the incidence of liquids flowing into the quarry hole and creating lag.

rftools-1.10-5.22
mcjtylib-1.10-1.9.9
I appreciate that these are a little out of date but we're still waiting for the admins to update the server. Apologies if these have already been addressed.

**Comment by McJty** [comment] 2016-09-28 15:50
It does destroy water source blocks. But the problem is that these reform very quickly in many cases. Running the quarry a few times over the same place usually helps with this

As to the things it can't mine. By default the builder skips things that have tile entities. You can change that in the config.

**Comment by xenoflot** [comment] 2016-09-28 18:50
Ah, I see. That makes sense.  Would it be practical for the quarry, on destroying a fluid source block to do a search/replace-with-dirt on immediately adjacent blocks? I can't see that would slow things down too much, and it should solve both the problem of lava flows and water sources reforming.

**Comment by McJty** [comment] 2016-09-28 18:55
It would complicate things considerably because then it would have to keep track of that dirt to remove it later

**Comment by xenoflot** [comment] 2016-09-28 19:02
In theory it should only need to place dirt in the direction it's heading, thus that dirt would be taken care of in the natural quarry process.

**Comment by xenoflot** [comment] 2016-09-28 19:07
And to be honest, there's already quite a bit of detritus left behind with the existing system from things like auto-generated cobble anyway, so I feel a small amount of dirt wouldn't too troublesome.

**Comment by MichaelHillcox** [comment] 2020-03-26 01:17
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Closed by MichaelHillcox** 2020-03-26 01:17 UTC
