### ISSUE TITLE
Crash when moving with builder

### ISSUE THREAD

**Issue by Sp3rw3r** [McJtyMods/RFTools#849] opened 2016-11-17 10:44 UTC
When placing a non standard block like a bed or an block from enderio the game crashes.

[crashreport](http://pastebin.com/Fy3idnVB)

**Comment by McJty** [comment] 2016-11-17 11:02
More info please. What exactly are you doing? What mode? What version of rftools?

**Comment by Sp3rw3r** [comment] 2016-11-17 11:14
Move option. 5.59. I see there is a newer version. Testing that now. More info when problem persists.

**Comment by Sp3rw3r** [comment] 2016-11-17 11:36
Tried with version 1.10-5.60

Trying to move [this](http://imgur.com/a/eoGVS): a floor with 9 planks, a chest and a bed to [here](http://imgur.com/a/hivkE)

Removed all other mods. [new crashreport](http://pastebin.com/RfQgvDpU)

**Comment by McJty** [comment] 2016-11-17 11:37
Ok, I will check it out

**Comment by McJty** [comment] 2016-11-18 13:10
I cannot reproduce this...

**Comment by inviktus** [comment] 2017-09-29 00:39
https://forum.feed-the-beast.com/threads/rf-tools-builder-block-crashing-game.258468/

I am having this same issue.

**Comment by MichaelHillcox** [comment] 2020-03-26 01:49
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Closed by MichaelHillcox** 2020-03-26 01:49 UTC
Labels: Cannot Reproduce
