### ISSUE TITLE
Remote Storage Flicker/Loses Connection 

### ISSUE THREAD

**Issue by KAfable** [McJtyMods/RFTools#1196] opened 2017-05-21 15:57 UTC
Minecraft 1.11
Version: 1.1x-6.01

Pack: All the Mods 2

A modular storage chest with a linked remote storage module constantly flickers on and off. I'm using 2 storage modules and a remote storage block as an ender chest system to transfer items from mob farms wirelessly. The Remote Storage Module seems to flicker on and off constantly in the modular storage block, as item stacks go from 1 - 50/ 300 to 0/0 stacks. 

The Remote Storage Block is constantly powered by an RFTools Powercell, and they are only separated by a couple chunks apart.

Cross dimension access is disabled,

**Comment by McJty** [comment] 2017-05-22 06:33
This has been reported before but I have never been able to reproduce it. Can you give me a bit more information:

* Server or single player?
* Using a chunkloader?
* What do you mean by 'as item stacks go from 1/50/300 to 0/0'?

**Comment by Armigus** [comment] 2017-08-01 13:12
When I have more than one storage module in a remote storage block, the remote module automatically swaps through them, displaying each in turn.  This occurs if only one of the modules has anything in it.  When I put some items in another module, then the swapping stops and it works normally.  It took a few seconds for the system to recover when I added a non-empty module to a block where the flickering was occurring.

**Comment by Armigus** [comment] 2017-08-01 13:23
Update: Some flickering still occurs but it's more manageable.  I can confirm that neither power (fed with cryotheum fluxduct) nor chunk loading (right next to block and cc chunk loader active) is responsible.  One of the slots in the remote storage is empty and the remote module in the tablet might be swapping to it on occasion, causing the flicker.

**Comment by prothseda** [comment] 2017-12-31 02:47
Hey all,

I was having the same issue today. I believe I've found a cause and a way to reproduce the problem consistently on my end - MC 1.12.2 w/ RFTools 1.12-7.15

So I placed down the Remote Storage and the Modular storage without modules in them. I powered up the RS and placed in a T3 storage module and linked a remote module. I then placed it in the RS which flickered on and off. I then break the RS block, with the module inside, and place it back again. The flickering is not gone, but it's now only once or twice every few minutes, opposed to every second or two.

Reproduction is easy, just break everything and place it back in the order above and the issue comes straight back. @McJty if you're unable to reproduce on your end I'm happy to record the reproduction on my end if that helps.

**Comment by kepler155c** [comment] 2018-02-21 10:45
I have this issue in both MC 1.7.10 and 1.11. I found in 1.7.10 that the issue occurs if the storage unit and the remote storage unit are in different chunks.

**Comment by dm8mydog** [comment] 2018-02-25 22:02
It's occuring for me in Forever Stranded Lost souls RFTools 1.12-7.29

happens when I'm in the same chunk so chunk loading is not the cause. It flickers when I'm using it on a portable tablet, but it does not happen when I'm using it via a modular storage.

I tried surrounding the remote storage with capacitors  and/or fluxducts.. still happens.
I tried removing all points of access and leaving just the one on my one tablet, and it still happens.
I tried using a different battery (Thermal's flux capacitor, and Actually addition's battery)
I tried moving it away from my storage scanner's range.

...it keeps flickering, any advice?

**Comment by dm8mydog** [comment] 2018-02-25 22:25
log entry (but this looks unrelated)
[main/ERROR] [mcjty.lib.varia.Logging]: java.lang.RuntimeException: Internal error! getSideWindowBounds() called before initGui!

**Comment by dm8mydog** [comment] 2018-02-25 23:44
oooh, ignore me, Issue was probably caused by too many 'dying withers that should have actually died ages ago' (or maybe xp orbs)

if you care,
There appears to be an issue when trying to use a Compact machine as a wither farm (with Industrial forgoing wither builder/mob crusher), I gave it a small inventory of soul sand and skulls and let it run, thinking rightly it should be done within a day, and it was, but when I visited it there was some loud noise and an explosion of -something- (xp orbs?) and then whatever was making a mess fixed itself.

Question for you: Why was this affecting the tablet w/remote storage but NOT affecting the tablet w/storage scanner? food for thought :)

**Comment by Tri-eDge17** [comment] 2019-10-15 10:17
Hi @McJty ,

I've been still encountering this flickering bug lately. Sorry but it might be related to tps on the world. I do not encounter this on a fresh world but it keeps flickering on my Single player world. TPS on this world is already at 10 TPS on average due to the amount of automated systems.

**Closed** 2020-03-26 03:14 UTC
Labels: Cannot Reproduce, Investigation, bug
