### ISSUE TITLE
Blocks cant be quarried inside of Minecolonies boarders

### ISSUE THREAD

**Issue by djpanda** [McJtyMods/RFTools#1135] opened 2017-04-08 14:04 UTC
RFTools Builderblock with Quarry Card can be placed but not able to remove any Block inside the colonyboarders

https://github.com/Minecolonies/minecolonies/issues/753#issuecomment-292717309

**Comment by McJty** [comment] 2017-04-08 14:23
That's not something I can do much about I think

**Comment by djpanda** [comment] 2017-04-08 17:38
The Builder are working the blocks up and lyer by leyer in his chunks but they didnt get removed in the world

**Comment by McJty** [comment] 2017-04-08 17:40
The builder uses standard block breaking mechanics so if those are failing then something in minecolonies is most likely broken. Make sure you're using the latest version of RFTools because I *did* so some fixes related to that

**Comment by djpanda** [comment] 2017-04-08 23:02
We are using rftools-1.1x-5.91.jar

**Comment by Terpo** [comment] 2017-08-13 14:38
Just an update here: problem still exists. The builder can build stuff but can't break anything. 
compatlayer-1.11.2-0.2.9.jar
minecolonies-universal-1.11.2-0.8.3293.jar
rftools-1.1x-6.12.jar

**Comment by McJty** [comment] 2017-08-13 17:07
This must be something on their side as the builder just use normal breaking mechanics

**Comment by MichaelHillcox** [comment] 2020-03-26 03:05
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Closed by MichaelHillcox** 2020-03-26 03:06 UTC
Labels: Maybe Other Mods Bug

**Comment by djpanda** [comment] 2020-03-26 04:00
Didnt tested it with the Quarry Card on newer versions but tried to place Blocks with the RF Builder and ShapeCard on minecolonies-0.11.776-ALPHA-universal.jar. Didnt worked as well on version. tried to add RFBuilder as Officer and it didnt change anything

**Comment by MichaelHillcox** [comment] 2020-03-26 12:42
If you can test and it's still an issue then let us know in a new issue, I'm currently attempting to reduce the amount of old or stale issues so I'm closing anything that is "likely" to no longer be an issue with newer versions

**Comment by TheKrowi** [comment] 2020-04-23 14:13
I was looking for the same problem when I stumbled upon this issue. It still exists and is reproducible by setting `B:enableColonyProtection=true` in minecolonies.cfg (or ingame through the mod options menu). I had this set to true by default. When putting it to false and trying to run the builder with the clearing shape card again actually removed the blocks.
