### ISSUE TITLE
Screens not connecting to controller in my modpack. 

### ISSUE THREAD

**Issue by mrtopf** [McJtyMods/RFTools#667] opened 2016-08-02 21:05 UTC
Today I tried to setup a screen with a screen controller but the screen didn't want to connect to the controller. Controller has power and I scanned and now it says "1 connected screens". The screen though has a [NO POWER] in the tooltip (and does not work of course). 

I am in 1.10.2, Forge 2044, RFTools 5.10 and McJtyLib 1.9.9 (and various other mods)

I also checked now in a new instance with just rftools and there it worked. So are there any known incompatibilities you are aware of?

When I have some time I might go ahead and remove mods to see which one creates this issue. I will update this issue then.

**Comment by McJty** [comment] 2016-08-12 09:40
We had a thing like this on BTM (Better Then Minecon) and it was actually caused by another mod. Not sure which one though. Do you have a modlist?

**Comment by mrtopf** [comment] 2016-08-12 10:11
Ah thanks, good to know. I need to check if there is a way to export this from curse but otherwise I will simply take the modlist from the mods folder. Need to do it later though when I am back home. In case the mod booth list on http://btm.asie.pl/16.2/index2.html is the right one here is a list of mods I also have installed (for 1.10.2 and from memory):

Blood Magic
Chisel
CraftingCraft
Crafting Tweaks
Dark Utilities
Deep Resonance
Ender IO
Fancy Fluid Storage
Forestry
IndustrialCraft 2
NotEnoughWands
OpenComputers
Random Things
RFTools
Roots
Soul Shards: The Old Ways
The One Probe

But as said, a complete list will follow later (and I will also test it again as some mods have updated in the meanwhile)

**Comment by mrtopf** [comment] 2016-08-13 22:32
So I checked it again and I got the elevator now working (maybe I didn't connect it before but I think I remember also other modules not working like text or clock). The WAILA tooltip still shows not connected, no power though. 

My mods are:

```
AgriculturalExpansion[1.9.4][1.10.2]-r1.2.1.jar
armorplus-1.10.2-6.0.1.0.jar
Aroma1997Core-1.9.4-1.1.0.3.jar
AromaBackup-1.9.4-1.0.1.1.jar
Bagelsmore-1.0.0.jar
bdlib-1.12.0.2-mc1.10.2.jar
BetterAchievements-1.10.2-0.3.0.29.jar
BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar
BetterFps-1.3.2.jar.disabled
BiomesOPlenty-1.9.4-4.1.0.2065-universal.jar
BlockDrops-1.10.2-1.0.10.jar.disabled
BloodMagic-1.9.4-2.0.3-54.jar
Bookshelf-1.10.2-1.3.0.282.jar
Chameleon-1.9.4-2.1.6.jar
Chisel-MC1.9.4-0.0.6.33.jar
chiselsandbits-11.10.jar
CookingForBlockheads_1.10.2-4.1.12.jar
CraftingCraft_1.10.2-4.1.5.jar
CraftingTweaks_1.10.2-6.1.9.jar
CreeperAwareness-2.0.2-1.10.2.jar
cxlibrary-1.10.2-1.2.2.jar
DarkUtilities-1.10.2-1.1.3.70.jar
deepresonance-1.10-1.2.1beta38.jar
DoomlikeDungeons-1.8.13-MC1.10.jar
ElecCore-1.9.4-1.5.303.jar
EnderCore-1.10.2-0.4.1.47-beta.jar
EnderIO-1.10.2-3.0.1.92_beta.jar
endertanks-1.10.0-1.4.1.jar
enderthing-1.10.2-0.6.11.jar
EnderZoo-1.10-1.2.3.43.jar
Excore-1.6.1-1.10.2.jar
extrablocks-1.0.2.jar
extrautils2-1.10.2-alpha-1.0.1.jar
Fancy Fluid Storage-1.9.4-1.6.4-b28.jar
FastLeaveDecay-MC1.9.4-1.2.1.jar
FlatBedrock-1.2.1_1.9.4.jar
flatcoloredblocks-mc1.10-v4.1.jar
forestry_1.10.2-5.2.8.234.jar
FTBLib-1.9.4-2.1.0-pre2.jar
FTBUtilities-1.9.4-2.1.0-pre2.jar
FusionLord's Patrons-1.10.2-b2.jar
gendustry-1.6.4.8-mc1.10.2.jar
Graves-1.10.2-b28-universal.jar
Guide-API-1.9.4-2.0.0-40.jar.disabled
h3ntlibs
ic2
immcraft-1.9.4-1.1.7.jar
industrialcraft-2-2.6.37-ex110.jar
InGameInfoXML-1.10.2-2.8.1.85-universal.jar
inventorysorter-1.10-0.10.0+42.jar.disabled
InventoryTweaks-1.61-58.jar
ironchest-1.10.2-7.0.9.796.jar
jefb_1.10.2-1.0.3.jar
jei_1.10.2-3.8.1.242.jar
journeymap-1.10.2-5.2.4-unlimited.jar
JustEnoughResources-1.10.2-0.4.6.42.jar
LunatriusCore-1.10.2-1.1.2.36-universal.jar
malisiscore-1.9.4-4.1.1.jar
malisisdoors-1.9.4-5.0.2.jar
Mantle-1.10.2-0.10.4.jar
mcjtylib-1.10-1.9.9.jar
MCMultiPart-1.2.1-universal.jar
MmmMmmMmmMmm-1.11.jar
MoreFurnaces-1.10.2-1.8.2.jar
moreoverlays-1.6-mc1.9.4.jar
MouseTweaks-2.6.4-mc1.10.2.jar
Mychunkloader-1.9.4-1.10.2-03.jar
Neat 1.3-11.jar
notenoughwands-1.9.4-1.3.5.jar
OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
Pam's HarvestCraft 1.9.4-1.10.2b.jar
Psi-r1.0-37.jar
Quark-beta-50.jar
RandomThings-MC1.10.2-3.7.5.jar
RebornCore-1.10.2-2.6.2.15-universal.jar
RecallStones-1.10.2-0.6.3.jar
Reliquary-1.10.2-1.3.3.455.jar
resources
rftools-1.10-5.14.jar
rftoolsdim-1.10-4.30beta47.jar
RoguelikeDungeons-1.10.2-1.5.4.jar
roots-1.10.2-0.110.0.jar
RouterReborn-1.10.2-4.0.1.19_universal.jar
Ruins-1.10.2
Ruins-1.10.2.jar
Ruins-1.10.2.zip
shetiphiancore-1.10.0-3.3.0.jar
SlashBlade-mc1.9.4-r15b.jar
sokratiscore-1.10.2-1.0.1.jar
SoulShards-TOW-1.10.2-2.6.1-41.jar
StorageDrawers-1.10.2-3.2.3.jar
TConstruct-1.10-2.3.3a.jar
teleporters-1.1.3.jar
Teletubbies-1.9.4_1.10.x-0.6.0.jar
thedragoncore-1.1.0.jar
theoneprobe-1.10-1.0.15.jar
Waila-1.7.0-B3_1.9.4.jar
WailaHarvestability-mc1.10-1.1.7.jar
Wawla-1.10.2-2.3.0.197.jar
```

I will do a little bit of testing in other configurations.

**Comment by MichaelHillcox** [comment] 2020-03-26 01:11
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Closed** 2020-03-26 01:11 UTC
Labels: 1.10.2, Cannot Reproduce
