### ISSUE TITLE
[1.10.2] Wrench causes CTD when used on Endergenic Generator

### ISSUE THREAD

**Issue by AlphaChimaera89** [McJtyMods/RFTools#637] opened 2016-07-22 06:27 UTC
RFTools wrench on Select mode causes a CTD when used on Endergenic Generators. 

Minecraft 1.10.2
rftools-1.10-5.06
Forge version 12.18.1.2011

**Comment by McJty** [comment] 2016-08-22 04:59
I cannot reproduce this. Do you have a crashlog?

**Comment by MichaelHillcox** [comment] 2020-03-26 01:07
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Closed by MichaelHillcox** 2020-03-26 01:07 UTC
Labels: 1.10.2, Cannot Reproduce, question
