### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by MVethana** [McJtyMods/RFTools#1861] opened 2018-10-24 17:13 UTC
Issue description: 

https://pastebin.com/SVrgRdCG

Crash upon load when entering newly generated RF Tools dimension. Can't teleport either as the game crashes while it is trying to generate terrain. What are my options for getting out of this world?

**Comment by McJty** [comment] 2018-10-24 17:18
You can probably use mcedit to change your player position.

**Comment by josephcsible** [comment] 2018-10-24 23:17
Duplicate of McJtyMods/RFToolsDimensions#238

**Closed by josephcsible** 2018-10-24 23:17 UTC
