### ISSUE TITLE
[1.10.2] [Bug] Elytra can not be pulled from storage scanner

### ISSUE THREAD

**Issue by Dijkstra1** [McJtyMods/RFTools#715] opened 2016-08-29 08:37 UTC
I made repairer from another mod, and then i linked it to storage scanner so I could repair items any where, but when repairing the I notice a bug I could not get it back though, storage scanner tablet, in [Video 1](https://github.com/McJty/RFTools/files/442010/mcjty.zip), demonstrate this, but at this point though it mod incompatibly, so I tried taking using my storage system and that did work from the storage scanner tablet or storage scanner itself, [Video 2](https://github.com/McJty/RFTools/files/442018/mcjty2.zip)

**Comment by Dijkstra1** [comment] 2016-09-03 16:27
If helps same problem with the industrial craft MFSU.

**Comment by McJty** [comment] 2016-09-21 11:03
I cannot reproduce this problem. Do you still have it with latest versions?

**Comment by Dijkstra1** [comment] 2016-09-27 09:44
I will test it again when i get a chance, but Minecraft has not high on my priorities lately, and do not see my self doing so for at least a few week weeks.

**Comment by McJty** [comment] 2016-09-27 09:49
I actually have been able to reproduce this with deep resonance crystals

**Comment by Dijkstra1** [comment] 2016-09-27 16:25
I have noticed, other mod items it happening to, like I said above it may not be a bad idea to test on a server as that is what I had the original issue on, I find a lot of the bugs that I find may caused by me any a server, but do not think to mention and it seems most modders do not think to try and reproduce on a server.

**Comment by McJty** [comment] 2016-09-27 16:46
Well I had it on my LP single player world so not server related

**Comment by McJty** [comment] 2016-09-28 11:39
Well apparently the bug for the crystals was in Deep Resonance. It is fixed now. So that means I still cannot reproduce this. However, the bug with DR was related to DR removing some NBT client side only which means that RFTools could not find it in the scanner. I wonder if you have some kind of mod that also messes with client side NBT for items to add information or anything

**Comment by Dijkstra1** [comment] 2016-09-29 08:59
Well i am using the pack [All the mods](https://mods.curse.com/modpacks/minecraft/242462-all-the-mods), I have added [The Earth Mod](https://minecraft.curseforge.com/projects/the-earth-mod),  [Translocators](http://chickenbones.net/Pages/links.html) (this before they added to the pack), [Better builders wands](https://minecraft.curseforge.com/projects/better-builders-wands) and mod of my own for alpha testing (does not do anything with NBT, only client side rendering at the moment), as which mod I think it is down, I can not say if i had the time I would look into seeing if any of the added something to the Elytra, in a few I will update the pack and see if I still happens, I guess if happen to item from another mod, I will have to open an issue with get them to remove client side NBT.

**Closed** 2019-10-11 15:35 UTC
Labels: 1.10.2, bug, needs response from reporter
