### ISSUE TITLE
FluxedRedstone Cables and Power Cells wont Output Energy

### ISSUE THREAD

**Issue by kaidenyo** [McJtyMods/RFTools#984] opened 2017-01-16 01:23 UTC
Hey, I have a Power Cell hooked up to Solar Panels with FluxedRedstone Cables. The INPUT works just fine ( RF Gen -> Cable -> Cell ), but the Output doesnt work ( Power Cell -> Cable -> Farm ). PowerCells also do not work with the AE Energy-Acceptor.

**Comment by McJty** [comment] 2017-01-16 04:20
That's not a bug with the powercells. They work fine with all other mods that use RF properly. I guess these mods implement things wrong in some way. You did configure the output right for the powercell?

**Comment by kaidenyo** [comment] 2017-01-16 10:39
Yep. I did configure the output right, because it worked when using it like hits Cable -> PowerCell -> Farm, but it still did not work the same way on the AE Energy Acceptor or with the FluxedRedstone Cables.

**Comment by McJty** [comment] 2017-01-16 10:40
Please report to those mods first. I'm not closing this yet because I want to be sure but I very strongly suspect the issue is on their side

**Closed** 2020-03-26 02:31 UTC
Labels: Maybe Other Mods Bug
