### ISSUE TITLE
[1.10.x] Rftools elevator and minecolonies

### ISSUE THREAD

**Issue by Daniele05062006** [McJtyMods/RFTools#1796] opened 2018-06-24 20:26 UTC
I have installed rftools and minecolonies in the same modpack, when i build a elevator it doesn't work in the colonies but when I try to build it out of the colonies, it work
Versions:
Minecraft: 1.10.2
Rftools:1.1x-7.16
Minecolonies:1.10.2-0.9.7587

**Comment by McJty** [comment] 2018-06-25 02:42
Did you report this to minecolonies as well? This has been reported before and I believe it was an issue on their side

**Comment by tie** [comment] 2020-01-12 22:20
It is an issue on their side, and I believe it’s caused by colony protection. A temporary workaround is to disable colony protection (or perhaps whitelisting block interactions on the whole elevator path).

See https://github.com/ldtteam/minecolonies/issues/2561

**Comment by MichaelHillcox** [comment] 2020-04-12 19:54
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Closed** 2020-04-12 19:54 UTC
