### ISSUE TITLE
Crafting via the Storage Scanner (or Tablet) does not count as crafting the item in Statistics or other mods

### ISSUE THREAD

**Issue by aaronhowser1** [McJtyMods/RFTools#1839] opened 2018-09-05 13:07 UTC
Issue description: 
Thaumcraft requires I craft one of each Thaumium tool, which I did via the Storage Tablet. It didn't get detected as crafted by the mod or by Minecraft's statistics. This is a problem for any other mod that requires you craft items, like Thaumcraft or quest mods.

Steps to reproduce: 
Crafting anything and then check statistics.

Versions:

Minecraft: 1.12.2
Forge: forge-14.23.4.2759
McJtyLib: mcjtylib-1.12-3.0.3
RFTools: rftools-1.12-7.55

**Comment by josephcsible** [comment] 2018-09-05 15:53
Duplicate of #1469

**Closed by josephcsible** 2018-09-05 15:53 UTC
