### ISSUE TITLE
Mobs not making any sounds in dimensions

### ISSUE THREAD

**Issue by ghost** [McJtyMods/RFTools#529] opened 2016-05-08 20:48 UTC
Forgot to report this. Almost all sounds are muted in rftools dimensions. So far I I can only confirm to hear the sound of collecting exp playing as usual. Even creeper explosions are completely silent. 

This is the case for all dimensions I encountered so far.

**Comment by McJty** [comment] 2016-05-09 02:55
What? That's extremely weird as I don't do anything in relation to sound. But anyway, I need to know what version of MC + rftools that you're using

**Comment by Tridon343** [comment] 2016-05-12 08:34
rftools-1.9.0-4.46
MC 1.9; forge 1.9-12.16.1.1889 

here is a full log of me walking around, killing a few mobs and opening chests. 
http://pastebin.com/HrhtMSfA

I still get sounds from taking damage, collecting exp or landing on the ground, but all other sounds seem not to play. Sounds play fine in the overworld.

**Comment by McJty** [comment] 2016-05-12 12:48
I cannot reproduce this. Must be some kind of weird mod interaction or something.

**Comment by MichaelHillcox** [comment] 2020-03-26 01:01
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Closed by MichaelHillcox** 2020-03-26 01:01 UTC
Labels: Cannot Reproduce
