### ISSUE TITLE
Builder Block offset is just ignored

### ISSUE THREAD

**Issue by SummaryPick** [McJtyMods/RFTools#1009] opened 2017-01-26 10:42 UTC
My builder block with fortune quarry card is acting like the builder at "NE, NW, SE, SW" corner buttons are on whenever it actually isn't selected.  The offset is 2000+ blocks away but where it actually mines starts 1 block way from the builder.  There is no setting with the builder at the corner selected, but it's acting like there is, any help?

**Comment by SummaryPick** [comment] 2017-01-26 17:35
Just a little more info.

This is the settings on the Fortune Quarry card
<img width="719" alt="screen shot 2017-01-26 at 11 26 40 am" src="https://cloud.githubusercontent.com/assets/24310006/22342822/5339de62-e3bb-11e6-9231-3c93d0d38fc3.png">

This is the preview turned on with the same settings on that card installed into the builder block
![2017-01-26_11 30 34](https://cloud.githubusercontent.com/assets/24310006/22342842/67ddcf7c-e3bb-11e6-88ff-6e774ad8b699.png)

Minecraft 1.10.2

**Comment by McJty** [comment] 2017-01-26 18:06
I'll check it out but the problem is that your offset overflows the maximum allowed. You can raise this value in the config if you are single player. But it certainly needs better error checking

**Comment by SummaryPick** [comment] 2017-01-26 20:17
Thanks for the response, ill check this out

**Comment by MichaelHillcox** [comment] 2020-03-26 02:37
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Closed** 2020-03-26 02:38 UTC
