### ISSUE TITLE
Storage modules deleting items on upgrade.  1.11.2  1.1x-5.90  .2260

### ISSUE THREAD

**Issue by GridM0nkey** [McJtyMods/RFTools#1110] opened 2017-03-27 09:01 UTC
Hi,

So playing Rax Pack2 beta on server. Set up modular storage, made a tier one, loaded it up, 97 item stacks, pulled it out and upgraded it to a tier 2 in a vanilla crafting table used JEI + to load the table. poof all items gone. recreated in single player. Also tested building it by hand, no JEI + sign same results, eats the items.

minecraft 1.11.2
rftools 1.1x-50
forge .2260

thanks

**Comment by McJty** [comment] 2017-03-28 11:33
Version 1.1x-50? That doesn't seem right

**Comment by McJty** [comment] 2017-03-28 11:35
I cannot reproduce this...

**Comment by GridM0nkey** [comment] 2017-03-28 21:00
I might have miss copied 1.1x-50, but i think that is what i got from the mod options listing inside minecraft. In fact i think i did. the jar is rftools-1.1x-5.90  So sorry about that. Missed a number which im sure threw you off in all of you testing.

**Comment by McJty** [comment] 2017-03-29 04:07
Nah that makes no difference. It still isn't failing for me. I don't know why this would be. Perhaps some mod affects crafting or something?

**Comment by GridM0nkey** [comment] 2017-03-29 04:18
ok ill chat with Rorax see what we can find

**Comment by dannyr-git** [comment] 2019-04-22 04:43
This is also occuring on FTB Interactions

**Comment by McJty** [comment] 2019-04-22 04:50
@Orichlol can you describe exactly what you did?

**Comment by dannyr-git** [comment] 2019-04-27 00:26
It's a function of FTB Interactions w/ Gregtech.  If you upgrade via one of the machines, it deletes.

It's functioning as intended in this pack.

**Comment by MichaelHillcox** [comment] 2020-03-26 02:59
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Closed by MichaelHillcox** 2020-03-26 02:59 UTC
Labels: Cannot Reproduce
