### ISSUE TITLE
Storage Scanner Console Error On Use

### ISSUE THREAD

**Issue by mrdeadlocked** [McJtyMods/RFTools#1377] opened 2017-09-26 00:32 UTC
We are getting the bottom error when intermittently when storage scanners are being accessed.

Modpack: All The Mods 3
RFtools Version: 6.13
Minecraft Version 1.12.1

java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_03-Ubuntu]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_03-Ubuntu]
at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_03-Ubuntu]
Caused by: java.lang.NullPointerException
at mcjty.lib.container.InventoryHelper.getItems(InventoryHelper.java:140) ~[InventoryHelper.class:?]
at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.lambda$performSearch$22(StorageScannerTileEntity.java:436) ~[StorageScannerTileEntity.class:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_03-Ubuntu]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_03-Ubuntu]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_03-Ubuntu]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_03-Ubuntu]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_03-Ubuntu]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_03-Ubuntu]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_03-Ubuntu]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_03-Ubuntu]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_03-Ubuntu]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_03-Ubuntu]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_03-Ubuntu]
at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.performSearch(StorageScannerTileEntity.java:435) ~[StorageScannerTileEntity.class:?]
at mcjty.rftools.blocks.storagemonitor.SearchItemsInfoPacketServer.onMessageServer(SearchItemsInfoPacketServer.java:61) ~[SearchItemsInfoPacketServer.class:?]
at mcjty.lib.network.clientinfo.PacketGetInfoFromServer$Handler.lambda$onMessage$1(PacketGetInfoFromServer.java:53) ~[PacketGetInfoFromServer$Handler.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_03-Ubuntu]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_03-Ubuntu]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
... 5 more

**Comment by McJty** [comment] 2017-09-26 06:35
Can you describe how you get this?

**Comment by mrdeadlocked** [comment] 2017-09-26 13:03
I have a setup of Storage Drawers attached to a Drawer controller. Storage scanner has the drawer controller + 6 Actually Additions crates. I'll try to watch the log as I'm using the scanner to try and see what items out are causing the error.

**Comment by ouroborus** [comment] 2017-10-10 04:43
Is there some way to blacklist Storage Drawers in relation to the Storage Scanner?

**Comment by McJty** [comment] 2017-10-10 09:46
I'll try to reproduce this soon

**Comment by McJty** [comment] 2017-10-11 04:03
I cannot reproduce any of these problems with the latest version of storage drawers on 1.12.2

**Comment by ouroborus** [comment] 2017-10-11 08:01
I still get this exception but it doesn't happen nearly as often as it did. It's hard to reproduce now.

**Comment by ouroborus** [comment] 2017-10-27 18:18
Still getting this in 1.12-7.12.

**Comment by CommYutzy** [comment] 2017-12-05 00:14
I am getting this in my console as well. With mine it appears that the storage scanner is throwing the error when it attempts to scan Solar Flux Reborn solar panels. It happens every minute or so. Two members on my server are using both of the mentioned items in their bases.

Relevant mods:
mcjtylib-1.12-2.5.0
rftools-1.12-7.14
SolarFluxReborn_1.12.2-3.42r

[19:11:38] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at com.pengu.hammercore.tile.TileSyncable.getCapability(TileSyncable.java:228) ~[TileSyncable.class:?]
        at com.pengu.solarfluxreborn.te.SolarPanelTileEntity.getCapability(SolarPanelTileEntity.java:521) ~[SolarPanelTileEntity.class:?]
        at mcjty.lib.container.InventoryHelper.getItems(InventoryHelper.java:139) ~[InventoryHelper.class:?]
        at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.lambda$performSearch$21(StorageScannerTileEntity.java:439) ~[StorageScannerTileEntity.class:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_151]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_151]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_151]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_151]
        at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.performSearch(StorageScannerTileEntity.java:439) ~[StorageScannerTileEntity.class:?]
        at mcjty.rftools.blocks.storagemonitor.SearchItemsInfoPacketServer.onMessageServer(SearchItemsInfoPacketServer.java:61) ~[SearchItemsInfoPacketServer.class:?]
        at mcjty.lib.network.clientinfo.PacketGetInfoFromServer$Handler.lambda$onMessage$1(PacketGetInfoFromServer.java:53) ~[PacketGetInfoFromServer$Handler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]

**Comment by MichaelHillcox** [comment] 2020-03-26 03:41
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Closed by MichaelHillcox** 2020-03-26 03:41 UTC
